db:
  image: mongo
  ports:
    - "27017:27017"

dbseed:
  build: ./docker/dbseed
  links:
    - db

s3:
  image: lphoward/fake-s3
  ports:
    - "4569:4569"

s3seed:
  build: ./docker/s3seed
  links:
    - s3

app:
  build: .
  ports:
    - "3000:3000"
  links:
    - db
